import 'dart:ui';

import 'package:flutter_kostlivec/src/build_flavor.dart';
import 'package:flutter_kostlivec/src/state/serialization.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `config_state.dart` with the code generated by Freezed
part 'config_state.freezed.dart';
// optional: Since our ConfigState class is serializable, we must add this line.
// But if ConfigState was not serializable, we could skip it.
part 'config_state.g.dart';

@freezed
class ConfigState with _$ConfigState {
  const factory ConfigState({
    required BuildFlavor mode,
    @JsonKey(toJson: toJsonLocale, fromJson: fromJsonLocale) required Locale locale,
  }) = _ConfigState;

  factory ConfigState.fromJson(Map<String, Object?> json) => _$ConfigStateFromJson(json);
}
