// This file is "my_dummy_app_state.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `my_dummy_app_state.dart` with the code generated by Freezed
part 'my_dummy_app_state.freezed.dart';
// optional: Since our MyDummyAppState class is serializable, we must add this line.
// But if MyDummyAppState was not serializable, we could skip it.
part 'my_dummy_app_state.g.dart';

@freezed
class MyDummyAppState with _$MyDummyAppState {
  const factory MyDummyAppState({required int counter}) = _MyDummyAppState;

  factory MyDummyAppState.fromJson(Map<String, Object?> json) => _$MyDummyAppStateFromJson(json);
}
