// This file is "persistent_state.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `persistent_state.dart` with the code generated by Freezed
part 'persistent_state.freezed.dart';
// optional: Since our PersistentState class is serializable, we must add this line.
// But if PersistentState was not serializable, we could skip it.
part 'persistent_state.g.dart';

@freezed
class PersistentState with _$PersistentState {
  const factory PersistentState({String? language}) = _PersistentState;

  factory PersistentState.fromJson(Map<String, Object?> json) => _$PersistentStateFromJson(json);
}
